# Generated by Django 3.1.7 on 2021-04-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='image',
            field=models.BinaryField(blank=True),
        ),
    ]
